create table if not exists public.business_accounts (
  id bigint primary key,
  business_name text not null,
  owner_name text not null,
  email text not null,
  username text not null,
  password text not null,
  industry text not null,
  plan text not null,
  status text not null check (status in ('Trial', 'Active', 'Paused', 'Canceled')),
  seats integer not null default 1,
  monthly_price numeric not null default 0,
  next_billing date not null,
  created_at date not null,
  tenant_id text not null unique
);

create table if not exists public.registration_requests (
  id bigint primary key,
  applicant_name text not null,
  business_name text not null,
  issue text not null,
  submitted_at text not null,
  phone text,
  email text,
  username text,
  password text,
  industry text,
  plan text
);

create table if not exists public.site_admin_accounts (
  id integer primary key default 1 check (id = 1),
  name text not null,
  username text not null,
  password text not null,
  business text not null default 'Biz Track HQ'
);

create table if not exists public.platform_settings (
  id integer primary key default 1 check (id = 1),
  platform_name text not null default 'BizTrack',
  support_email text not null default 'support@biztrack.app',
  whatsapp_number text not null default '',
  default_plan text not null default 'Starter' check (default_plan in ('Starter', 'Growth', 'Scale')),
  maintenance_mode boolean not null default false
);

create table if not exists public.workspace_snapshots (
  tenant_id text primary key,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.workspace_sessions (
  username text primary key,
  tenant_id text not null,
  workspace_name text not null,
  owner_name text not null,
  password_hash text not null,
  updated_at timestamptz not null default now()
);

-- Each tenant can use a different fingerprint reader and integration adapter.
-- The app stores only the reader's opaque subject identifier, never a raw
-- fingerprint image or template.
create table if not exists public.biometric_devices (
  id bigint generated by default as identity primary key,
  tenant_id text not null references public.business_accounts (tenant_id) on delete cascade,
  provider text not null,
  model text not null,
  device_identifier text not null,
  bridge_url text,
  configuration jsonb not null default '{}'::jsonb,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  unique (tenant_id, device_identifier)
);

create table if not exists public.biometric_credentials (
  id bigint generated by default as identity primary key,
  tenant_id text not null,
  member_id bigint not null,
  member_name text not null,
  credential_id text not null,
  registered_at timestamptz not null default now()
);
create unique index if not exists biometric_credentials_tenant_credential_id_key on public.biometric_credentials (tenant_id, credential_id);

create table if not exists public.biometric_proofs (
  id bigint generated by default as identity primary key,
  tenant_id text not null,
  member_id bigint not null,
  action text not null check (action in ('sign-in', 'sign-out', 'mark', 'payroll')),
  credential_id text not null,
  verified_at timestamptz not null default now(),
  attendance_date date not null
);
alter table public.biometric_proofs drop constraint if exists biometric_proofs_action_check;
alter table public.biometric_proofs add constraint biometric_proofs_action_check check (action in ('sign-in', 'sign-out', 'mark', 'payroll'));

create table if not exists public.site_admin_snapshots (
  id integer primary key default 1 check (id = 1),
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.business_accounts enable row level security;
alter table public.registration_requests enable row level security;
alter table public.site_admin_accounts enable row level security;
alter table public.platform_settings enable row level security;
alter table public.workspace_snapshots enable row level security;
alter table public.workspace_sessions enable row level security;
alter table public.biometric_devices enable row level security;
alter table public.biometric_credentials enable row level security;
alter table public.biometric_proofs enable row level security;
alter table public.site_admin_snapshots enable row level security;

alter table public.platform_settings add column if not exists whatsapp_number text not null default '';
alter table public.business_accounts drop constraint if exists business_accounts_plan_check;
alter table public.registration_requests add column if not exists phone text;
alter table public.registration_requests add column if not exists email text;
alter table public.registration_requests add column if not exists username text;
alter table public.registration_requests add column if not exists password text;
alter table public.registration_requests add column if not exists industry text;
alter table public.registration_requests add column if not exists plan text;
alter table public.business_accounts drop constraint if exists business_accounts_plan_check;
alter table public.platform_settings drop constraint if exists platform_settings_default_plan_check;

drop policy if exists "Allow anonymous app access to business accounts" on public.business_accounts;
drop policy if exists "Allow anonymous app access to registration requests" on public.registration_requests;
drop policy if exists "Allow anonymous app access to site admin account" on public.site_admin_accounts;
drop policy if exists "Allow anonymous app access to platform settings" on public.platform_settings;
drop policy if exists "Allow anonymous app access to workspace snapshots" on public.workspace_snapshots;
drop policy if exists "Allow anonymous app access to workspace sessions" on public.workspace_sessions;
drop policy if exists "Allow anonymous app access to biometric credentials" on public.biometric_credentials;
drop policy if exists "Allow anonymous app access to biometric proofs" on public.biometric_proofs;
drop policy if exists "Allow anonymous app access to site admin snapshots" on public.site_admin_snapshots;
drop policy if exists "Members access their biometric devices" on public.biometric_devices;

create policy "Allow anonymous app access to business accounts"
  on public.business_accounts for all to anon using (true) with check (true);
create policy "Allow anonymous app access to registration requests"
  on public.registration_requests for all to anon using (true) with check (true);
create policy "Allow anonymous app access to site admin account"
  on public.site_admin_accounts for all to anon using (true) with check (true);
create policy "Allow anonymous app access to platform settings"
  on public.platform_settings for all to anon using (true) with check (true);
create policy "Allow anonymous app access to workspace snapshots"
  on public.workspace_snapshots for all to anon using (true) with check (true);
create policy "Allow anonymous app access to workspace sessions"
  on public.workspace_sessions for all to anon using (true) with check (true);
create policy "Allow anonymous app access to biometric credentials"
  on public.biometric_credentials for all to anon using (true) with check (true);
create policy "Allow anonymous app access to biometric proofs"
  on public.biometric_proofs for all to anon using (true) with check (true);
create policy "Allow anonymous app access to site admin snapshots"
  on public.site_admin_snapshots for all to anon using (true) with check (true);

insert into public.site_admin_accounts (id, name, username, password, business)
values (1, 'Platform admin', 'muli@track12', 'muli@track12', 'Biz Track HQ')
on conflict (id) do update set username = excluded.username, password = excluded.password;

insert into public.platform_settings (id)
values (1)
on conflict (id) do nothing;

-- Tenant isolation requires a Supabase Auth identity. The browser must never
-- be trusted to choose its own tenant_id.
create table if not exists public.tenant_memberships (
  user_id uuid not null references auth.users (id) on delete cascade,
  tenant_id text not null references public.business_accounts (tenant_id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'member')),
  created_at timestamptz not null default now(),
  primary key (user_id, tenant_id)
);

alter table public.tenant_memberships enable row level security;

create or replace function public.has_tenant_access(requested_tenant_id text)
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (select 1 from public.tenant_memberships where user_id = auth.uid() and tenant_id = requested_tenant_id);
$$;

create or replace function public.is_platform_admin()
returns boolean language sql stable
as $$
  select coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'platform_admin', false);
$$;

create or replace function public.claim_owner_tenant(requested_tenant_id text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  requested_username text;
  authenticated_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;
  select lower(username) into requested_username
  from public.business_accounts
  where tenant_id = requested_tenant_id;
  if requested_username is null or split_part(authenticated_email, '@', 1) <> requested_username then
    raise exception 'Tenant owner identity does not match';
  end if;
  insert into public.tenant_memberships (user_id, tenant_id, role)
  values (auth.uid(), requested_tenant_id, 'owner')
  on conflict (user_id, tenant_id) do update set role = 'owner';
  return true;
end;
$$;

create or replace function public.register_owner_biometric_legacy(
  requested_tenant_id text,
  requested_username text,
  requested_password text,
  requested_member_id bigint,
  requested_member_name text,
  requested_credential_id text,
  requested_registered_at timestamptz
)
returns void
language plpgsql
security definer
set search_path = public, private_biometrics
as $$
declare
  owner_password text;
begin
  select password into owner_password
  from public.business_accounts
  where tenant_id = requested_tenant_id
    and lower(username) = lower(requested_username);
  if owner_password is null or owner_password <> requested_password then
    raise exception 'Owner verification failed';
  end if;
  if exists (select 1 from private_biometrics.credentials where tenant_id = requested_tenant_id and member_id = requested_member_id) then
    raise exception 'This worker already has a biometric in this business';
  end if;
  insert into private_biometrics.credentials (tenant_id, member_id, member_name, credential_id, subject_identifier, registered_at)
  values (requested_tenant_id, requested_member_id, requested_member_name, requested_credential_id, requested_credential_id, requested_registered_at);
exception when unique_violation then
  raise exception 'This biometric is already registered in this business';
end;
$$;

create or replace function public.list_owner_biometric_credentials(
  requested_tenant_id text,
  requested_username text,
  requested_password text
)
returns table (credential_id text)
language plpgsql
security definer
set search_path = public, private_biometrics
as $$
declare
  owner_password text;
begin
  select password into owner_password
  from public.business_accounts
  where tenant_id = requested_tenant_id
    and lower(username) = lower(requested_username);
  if owner_password is null or owner_password <> requested_password then
    raise exception 'Owner verification failed';
  end if;
  return query
    select credentials.credential_id
    from private_biometrics.credentials
    where credentials.tenant_id = requested_tenant_id;
end;
$$;

drop policy if exists "Allow anonymous app access to business accounts" on public.business_accounts;
drop policy if exists "Allow anonymous app access to registration requests" on public.registration_requests;
drop policy if exists "Allow anonymous app access to site admin account" on public.site_admin_accounts;
drop policy if exists "Allow anonymous app access to platform settings" on public.platform_settings;
drop policy if exists "Allow anonymous app access to workspace snapshots" on public.workspace_snapshots;
drop policy if exists "Allow anonymous app access to workspace sessions" on public.workspace_sessions;
drop policy if exists "Allow anonymous app access to biometric credentials" on public.biometric_credentials;
drop policy if exists "Allow anonymous app access to biometric proofs" on public.biometric_proofs;
drop policy if exists "Allow anonymous app access to site admin snapshots" on public.site_admin_snapshots;

drop policy if exists "Users can read their tenant memberships" on public.tenant_memberships;
drop policy if exists "Members can read their business account" on public.business_accounts;
drop policy if exists "Platform admins manage business accounts" on public.business_accounts;
drop policy if exists "Anyone can submit a registration request" on public.registration_requests;
drop policy if exists "Platform admins manage registration requests" on public.registration_requests;
drop policy if exists "Platform admins manage site admin account" on public.site_admin_accounts;
drop policy if exists "Platform admins manage platform settings" on public.platform_settings;
drop policy if exists "Members access their workspace snapshot" on public.workspace_snapshots;
drop policy if exists "Members access their workspace session" on public.workspace_sessions;
drop policy if exists "Platform admins manage site snapshots" on public.site_admin_snapshots;

create policy "Users can read their tenant memberships" on public.tenant_memberships for select to authenticated using (user_id = auth.uid());
create policy "Members can read their business account" on public.business_accounts for select to authenticated using (public.has_tenant_access(tenant_id));
create policy "Platform admins manage business accounts" on public.business_accounts for all to authenticated using (public.is_platform_admin()) with check (public.is_platform_admin());
create policy "Anyone can submit a registration request" on public.registration_requests for insert to anon, authenticated with check (true);
create policy "Platform admins manage registration requests" on public.registration_requests for all to authenticated using (public.is_platform_admin()) with check (public.is_platform_admin());
create policy "Platform admins manage site admin account" on public.site_admin_accounts for all to authenticated using (public.is_platform_admin()) with check (public.is_platform_admin());
create policy "Platform admins manage platform settings" on public.platform_settings for all to authenticated using (public.is_platform_admin()) with check (public.is_platform_admin());
create policy "Members access their workspace snapshot" on public.workspace_snapshots for all to authenticated using (public.has_tenant_access(tenant_id)) with check (public.has_tenant_access(tenant_id));
create policy "Members access their workspace session" on public.workspace_sessions for all to authenticated using (public.has_tenant_access(tenant_id)) with check (public.has_tenant_access(tenant_id));
create policy "Members access their biometric devices" on public.biometric_devices for all to authenticated using (public.has_tenant_access(tenant_id)) with check (public.has_tenant_access(tenant_id));
create policy "Platform admins manage site snapshots" on public.site_admin_snapshots for all to authenticated using (public.is_platform_admin()) with check (public.is_platform_admin());

-- Reader subject identifiers and verification proofs are kept out of the
-- exposed public schema and out of workspace_snapshots.payload.
create schema if not exists private_biometrics;
revoke all on schema private_biometrics from anon, authenticated;
create table if not exists private_biometrics.credentials (
  id bigint generated by default as identity primary key,
  tenant_id text not null,
  member_id bigint not null,
  member_name text not null,
  credential_id text not null,
  provider text not null default 'legacy',
  device_identifier text not null default 'legacy',
  subject_identifier text not null default '',
  registered_at timestamptz not null default now()
);
alter table private_biometrics.credentials drop constraint if exists credentials_credential_id_key;
alter table private_biometrics.credentials add column if not exists provider text not null default 'legacy';
alter table private_biometrics.credentials add column if not exists device_identifier text not null default 'legacy';
alter table private_biometrics.credentials add column if not exists subject_identifier text not null default '';
update private_biometrics.credentials set subject_identifier = credential_id where subject_identifier = '';
with duplicate_credentials as (
  select id, row_number() over (partition by tenant_id, member_id order by registered_at, id) as duplicate_number
  from private_biometrics.credentials
)
delete from private_biometrics.credentials credentials
using duplicate_credentials duplicates
where credentials.id = duplicates.id
  and duplicates.duplicate_number > 1;
with duplicate_subjects as (
  select id, row_number() over (partition by tenant_id, subject_identifier order by registered_at, id) as duplicate_number
  from private_biometrics.credentials
)
delete from private_biometrics.credentials credentials
using duplicate_subjects duplicates
where credentials.id = duplicates.id
  and duplicates.duplicate_number > 1;
create unique index if not exists credentials_tenant_credential_id_key on private_biometrics.credentials (tenant_id, credential_id);
create unique index if not exists credentials_tenant_member_id_key on private_biometrics.credentials (tenant_id, member_id);
create unique index if not exists credentials_tenant_subject_identifier_key on private_biometrics.credentials (tenant_id, subject_identifier);
create table if not exists private_biometrics.proofs (
  id bigint generated by default as identity primary key,
  tenant_id text not null,
  member_id bigint not null,
  action text not null check (action in ('sign-in', 'sign-out', 'mark', 'payroll')),
  credential_id text not null,
  verified_at timestamptz not null default now(),
  attendance_date date not null
);
insert into private_biometrics.credentials (tenant_id, member_id, member_name, credential_id, registered_at)
select distinct on (tenant_id, member_id) tenant_id, member_id, member_name, credential_id, registered_at
from public.biometric_credentials
order by tenant_id, member_id, registered_at, id
on conflict (tenant_id, credential_id) do nothing;
insert into private_biometrics.proofs (tenant_id, member_id, action, credential_id, verified_at, attendance_date)
select tenant_id, member_id, action, credential_id, verified_at, attendance_date from public.biometric_proofs;
drop table if exists public.biometric_credentials;
drop table if exists public.biometric_proofs;

create or replace function public.register_biometric_credential(requested_tenant_id text, requested_member_id bigint, requested_member_name text, requested_credential_id text, requested_registered_at timestamptz)
returns void language plpgsql security definer set search_path = public, private_biometrics
as $$ begin
  if not public.has_tenant_access(requested_tenant_id) then raise exception 'Tenant access denied'; end if;
  if exists (select 1 from private_biometrics.credentials where tenant_id = requested_tenant_id and member_id = requested_member_id) then
    raise exception 'This worker already has a biometric in this business';
  end if;
  begin
    insert into private_biometrics.credentials (tenant_id, member_id, member_name, credential_id, subject_identifier, registered_at) values (requested_tenant_id, requested_member_id, requested_member_name, requested_credential_id, requested_credential_id, requested_registered_at);
  exception when unique_violation then
    raise exception 'This biometric is already registered in this business';
  end;
end; $$;

create or replace function public.record_biometric_proof(requested_tenant_id text, requested_member_id bigint, requested_action text, requested_credential_id text, requested_verified_at timestamptz, requested_attendance_date date)
returns void language plpgsql security definer set search_path = public, private_biometrics
as $$ begin
  if not public.has_tenant_access(requested_tenant_id) then raise exception 'Tenant access denied'; end if;
  insert into private_biometrics.proofs (tenant_id, member_id, action, credential_id, verified_at, attendance_date) values (requested_tenant_id, requested_member_id, requested_action, requested_credential_id, requested_verified_at, requested_attendance_date);
end; $$;

create or replace function public.list_biometric_credentials(requested_tenant_id text)
returns table (member_id bigint, credential_id text) language sql security definer set search_path = public, private_biometrics
as $$ select member_id, credential_id from private_biometrics.credentials where tenant_id = requested_tenant_id and public.has_tenant_access(requested_tenant_id); $$;

create or replace function public.delete_biometric_credential(requested_tenant_id text, requested_member_id bigint, requested_credential_id text)
returns void language sql security definer set search_path = public, private_biometrics
as $$ delete from private_biometrics.credentials where tenant_id = requested_tenant_id and member_id = requested_member_id and (requested_credential_id = '' or credential_id = requested_credential_id) and public.has_tenant_access(requested_tenant_id); $$;

create or replace function public.delete_owner_biometric_credential(
  requested_tenant_id text,
  requested_username text,
  requested_password text,
  requested_member_id bigint
)
returns void
language plpgsql
security definer
set search_path = public, private_biometrics
as $$
declare
  owner_password text;
begin
  select password into owner_password
  from public.business_accounts
  where tenant_id = requested_tenant_id
    and lower(username) = lower(requested_username);
  if owner_password is null or owner_password <> requested_password then
    raise exception 'Owner verification failed';
  end if;
  delete from private_biometrics.credentials
  where tenant_id = requested_tenant_id
    and member_id = requested_member_id;
end;
$$;

revoke all on function public.register_biometric_credential(text, bigint, text, text, timestamptz) from public, anon;
revoke all on function public.record_biometric_proof(text, bigint, text, text, timestamptz, date) from public, anon;
revoke all on function public.list_biometric_credentials(text) from public, anon;
revoke all on function public.delete_biometric_credential(text, bigint, text) from public, anon;
grant execute on function public.register_biometric_credential(text, bigint, text, text, timestamptz) to authenticated;
grant execute on function public.record_biometric_proof(text, bigint, text, text, timestamptz, date) to authenticated;
grant execute on function public.list_biometric_credentials(text) to authenticated;
grant execute on function public.delete_biometric_credential(text, bigint, text) to authenticated;
revoke all on function public.delete_owner_biometric_credential(text, text, text, bigint) from public;
grant execute on function public.delete_owner_biometric_credential(text, text, text, bigint) to anon, authenticated;
revoke all on function public.claim_owner_tenant(text) from public, anon;
grant execute on function public.claim_owner_tenant(text) to authenticated;
revoke all on function public.register_owner_biometric_legacy(text, text, text, bigint, text, text, timestamptz) from public;
grant execute on function public.register_owner_biometric_legacy(text, text, text, bigint, text, text, timestamptz) to anon, authenticated;
revoke all on function public.list_owner_biometric_credentials(text, text, text) from public;
grant execute on function public.list_owner_biometric_credentials(text, text, text) to anon, authenticated;
